### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by KBuild** [KBuild/switchkaitai#1]
- [x] Notify system
  - [x] choose SNS or E-mail -> E-mail
  - [x] add condition for notify
- [x] Retry & Timeout system
